language: go

before_install:
  - cd src && go get github.com/mattn/goveralls
# override default build command
script:
  - cd src &&  go test -v ./...
  - go build -o bodyweight.bin src/*.go
  - cd src && $GOPATH/bin/goveralls -service=travis-ci

deploy:
  - provider: lambda
    function_name: "bodyweight"
    region: "eu-west-1"
    role: "arn:aws:iam::854014537498:role/lambda_basic_execution"
    runtime: "go1.x"

    # workaround, for handler_name (concated via .)
    module_name: "bodyweight"
    handler_name: "bin"

#    on: master

# Skills Kit Trigger
#aws lambda add-permission
#    --function-name hello_world
#    --statement-id 1
#    --action lambda:InvokeFunction
#    --principal alexa-appkit.amazon.com
#    --event-source-token amzn1.ask.skill.xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Deployment of Skill possible !!